name: Simplified Deployment Pipeline
on:
  push:
    branches:
      - simplified

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t fressrg/trial1 .

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker Image to Docker Hub
        run: docker push fressrg/trial1:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Pull Docker Image from Docker Hub
        run: docker pull fressrg/trial1:latest

      - name: Upload SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key-pair.pem
          chmod 400 key-pair.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key-pair.pem ubuntu@${{ secrets.EC2_INSTANCE_PUBLIC_DNS }} << 'EOF'
            docker pull fressrg/trial1:latest
            docker rm -f devops-pso-container || true
            docker run -d -p 3000:3000 --name devops-pso-container fressrg/trial1
          EOF
